name: Build and Bump Version

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Bump Patch Version
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current version in file: $CURRENT_VERSION"

          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"

          NEW_PATCH=$((patch + 1))
          NEW_VERSION="$major.$minor.$NEW_PATCH"
          echo "Calculated new version: $NEW_VERSION"

          mvn versions:set -DnewVersion=$NEW_VERSION -DgenerateBackupPoms=false
          echo $NEW_VERSION

      - name: Build JAR Package
        run: mvn clean package
