name: Java CI with Maven

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      # Update the pom.xml version dynamically
      - name: Update project patch version with GitHub Run Number
        run: |
          mvn versions:set -DnewVersion=1.0.${{ github.run_number }} -DgenerateBackupPoms=false

      # Continue with your normal build process
      - name: Build with Maven
        run: mvn clean package
